SELECT SALES_OFFICE_NM ,USER_NM  FROM M_OFFICE LEFT OUTER JOIN T_USER ON M_OFFICE.OFFICE_CD = T_USER.OFFICE_CD;

SELECT SALES_OFFICE_NM ,USER_NM  FROM M_OFFICE RIGHT OUTER JOIN T_USER ON M_OFFICE.OFFICE_CD = T_USER.OFFICE_CD;