SELECT OFFICE_CD FROM T_USER WHERE OFFICE_CD = 3001;

SELECT USER_ID,USER_NM FROM T_USER WHERE BIRTHDAY >= '2000/01/01 00:00:00';

SELECT USER_NM FROM T_USER WHERE USER_NM LIKE '%田%';

SELECT BIRTHDAY FROM T_USER ORDER BY BIRTHDAY ASC;

SELECT MIN(BIRTHDAY),USER_NM FROM T_USER WHERE BIRTHDAY;

SELECT MIN(BIRTHDAY),USER_NM FROM T_USER WHERE BIRTHDAY;

SELECT *, IFNULL(BIRTHDAY,'2000-01-01') FROM T_USER;

SELECT BIRTHDAY, TIMESTAMPDIFF(YEAR, BIRTHDAY, '2020-6-1') AS age, USER_NM FROM T_USER 